using System.Collections.Immutable;
using System.Text;

namespace Endpointer;

internal static class SourceGenerationHelper
{
    public static string GenerateIEndpointInterface()
    {
        return """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Routing;

            namespace Endpointer;

            /// <summary>
            /// Marker interface for endpoint classes to be discovered by the source generator.
            /// </summary>
            public interface IEndpoint
            {
                void MapEndpoint(IEndpointRouteBuilder endpoints);
            }
            """;
    }

    public static string GenerateExtensionClass(ImmutableArray<EndpointInfo> endpoints)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
        sb.AppendLine("namespace Endpointer;");
        sb.AppendLine();
        sb.AppendLine("public static class EndpointerExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapEndpointer(this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var endpoint in endpoints)
        {
            GenerateEndpointRegistration(sb, endpoint);
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateEndpointRegistration(StringBuilder sb, EndpointInfo info)
    {
        sb.AppendLine($"        // {info.FullyQualifiedOuterName}");
        sb.AppendLine($"        new {info.FullyQualifiedOuterName}.{info.NestedEndpointName}().MapEndpoint(endpoints);");
        sb.AppendLine();
    }
}
