using System.Collections.Immutable;
using System.Text;

namespace Endpointer;

internal static class SourceGenerationHelper
{
    public static string GenerateIEndpointInterface()
    {
        return """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Routing;

            namespace Endpointer;

            /// <summary>
            /// Marker interface for endpoint classes to be discovered by the source generator.
            /// </summary>
            public interface IEndpoint
            {
                void MapEndpoint(IEndpointRouteBuilder endpoints);
            }
            """;
    }

    public static string GenerateExtensionClass(ImmutableArray<EndpointInfo> endpoints)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Endpointer;");
        sb.AppendLine();
        sb.AppendLine("public static class EndpointerExtensions");
        sb.AppendLine("{");

        GenerateAddEndpointerMethod(sb, endpoints);
        GenerateMapEndpointerMethod(sb, endpoints);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateAddEndpointerMethod(StringBuilder sb, ImmutableArray<EndpointInfo> endpoints)
    {
        sb.AppendLine("    public static IServiceCollection AddEndpointer(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var endpoint in endpoints)
        {
            sb.AppendLine($"        services.AddScoped<{endpoint.FullyQualifiedOuterName}>();");
        }

        if (endpoints.Length > 0)
        {
            sb.AppendLine();
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateMapEndpointerMethod(StringBuilder sb, ImmutableArray<EndpointInfo> endpoints)
    {
        sb.AppendLine("    public static IEndpointRouteBuilder MapEndpointer(this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var endpoint in endpoints)
        {
            sb.AppendLine($"        // {endpoint.FullyQualifiedOuterName}");
            sb.AppendLine($"        new {endpoint.FullyQualifiedOuterName}.{endpoint.NestedEndpointName}().MapEndpoint(endpoints);");
            sb.AppendLine();
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
    }
}
